version: '3.1'

services:
  mongodb:
    container_name: 'mongo_db'
    restart: always
    image: mongo
    volumes:
      - ~/home/docker/volumes/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: 123456789


  #mongo-express:
  # restart: unless-stopped
  #  ports:
  #    - "8081:8081"
  #  environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: mongoroot
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: 123456789
    #  ME_CONFIG_MONGODB_URL: mongodb://mongoroot:123456789@mongodb:27017/
